{% set name = "oschmod" %}
{% set version = "0.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oschmod-{{ version }}.tar.gz
  sha256: bec99216f31615ee653b2a5c87cacfb4e4b6184c0e9f71da186300dacae974f3

build:
  noarch: python
  entry_points:
    - oschmod = oschmod.cli:main
    - ochmod = oschmod.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pywin32-on-windows

test:
  imports:
    - oschmod
  commands:
    - pip check
    - oschmod --help
    - ochmod --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/yakdriver/oschmod
  summary: Windows and Linux compatible chmod
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sebastian-luna-valero
